alias: Agile_selected_session_1
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.minutes_until_session_1
    to: "0"
    for:
      hours: 0
      minutes: 0
      seconds: 30
condition:
  - condition: state
    entity_id: input_boolean.session_1_enable
    state: "on"
action:
  - variables:
      "StartTime:": "{% set startdate = states('input_text.session_1_start') %}"
      "EndTime:": "{% set enddate = states('input_text.session_1_end') %}"
  - service: select.select_option
    data:
      option: "{{states('input_text.session_1_start')}}"
    target:
      entity_id: select.givtcp_edxxxxxxx_charge_start_time_slot_1
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - if:
      - condition: template
        value_template: >-
          {{ states('select.givtcp_edxxxxxxx_charge_start_time_slot_1') !=
          states('input_text.session_1_start') }}
    then:
      - service: notify.persistent_notification
        data:
          message: "Inverter: Failed to set StartTime... trying again."
      - service: select.select_option
        data:
          option: "{{states('input_text.session_1_start')}}"
        target:
          entity_id: select.givtcp_edxxxxxxx_charge_start_time_slot_1
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
  - service: select.select_option
    data:
      option: "{{states('input_text.session_1_end')}}"
    target:
      entity_id: select.givtcp_edxxxxxxx_charge_end_time_slot_1
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - if:
      - condition: template
        value_template: >-
          {{ states('select.givtcp_edxxxxxx_charge_end_time_slot_1') !=
          states('input_text.session_1_end') }}
    then:
      - service: notify.persistent_notification
        data:
          message: "Inverter: Failed to set EndTime... trying again."
      - service: select.select_option
        data:
          option: "{{states('input_text.session_1_end')}}"
        target:
          entity_id: select.givtcp_edxxxxxxx_charge_end_time_slot_1
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
  - service: input_text.set_value
    data:
      value: >-
        Running session 1 at {{"\r\n"}} '({{now().strftime("%Y-%m-%d
        %H:%M:%S")}})' {{"\r\n"}} cost is
        "{{states('input_text.session_1_cost')}}" {{"\r\n"}} start time is 
        "{{states('input_text.session_1_start')}}" {{"\r\n"}} end time is
        "{{states('input_text.session_1_end')}}"
    target:
      entity_id: input_text.emulate_agile_action
mode: restart
