alias: Agile_selected_session_1
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.minutes_until_session_1
    to: "0"
    for:
      hours: 0
      minutes: 0
      seconds: 30
action:
  - service: script.agile_sol_check_control
    data: {}
  - service: script.agile_charge_battery
    data:
      title: Agile Charge session 1
      message: >-
        session 1 ran successfully at {{"\r\n"}}'({{now().strftime("%Y-%m-%d
        %H:%M:%S")}})' {{"\r\n"}} cost is
        "{{states('input_text.session_1_cost')}}"
      messagenotenabled: >-
        Soc is higher than target or {{"\r\n"}}  session 1 not enabled
        {{"\r\n"}}  Soc target "{{states('input_number.target_soc')}}"
        {{"\r\n"}} enabled is "{{states('input_boolean.session_1_enable')}}"
      messagefailstart: session 1  failed to load start time retrying
      messagefailend: session 1  failed to load end time retrying
      messageloadstart: >-
        start time of "{{states('input_text.session_1_start')}}" {{"\r\n"}} 
        Loaded
      messageloadend: end time of "{{states('input_text.session_1_end')}}" {{"\r\n"}} Loaded
      notification_id: id-001
      ses_detail: session_1_detail
      ses_cost: session_1_cost
      ses_start: session_1_start
      ses_end: session_1_end
      ses_enabled: session_1_enable
mode: restart
