alias: Agile_selected_session_5
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.minutes_until_session_5
    to: "0"
    for:
      hours: 0
      minutes: 0
      seconds: 30
action:
  - service: script.agile_charge_battery
    data:
      title: session 5
      message: >-
        session 5 ran successfully at {{"\r\n"}}'({{now().strftime("%Y-%m-%d
        %H:%M:%S")}})' {{"\r\n"}} cost is
        "{{states('input_text.session_5_cost')}}"
      messagenotenabled: session 5 is not enabled
      messagefailstart: session 5  failed to load start time retrying
      messagefailend: session 5  failed to load end time retrying
      messageloadstart: >-
        start time of "{{states('input_text.session_5_start')}}" {{"\r\n"}}
        Loaded
      messageloadend: end time of "{{states('input_text.session_5_end')}}" {{"\r\n"}} Loaded
      notification_id: id-005
      ses_detail: session_5_detail
      ses_cost: session_5_cost
      ses_start: session_5_start
      ses_end: session_5_end
      ses_enabled: session_5_enable
mode: restart
