alias: Agile_selected_session_4
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.minutes_until_session_4
    to: "0"
    for:
      hours: 0
      minutes: 0
      seconds: 40
action:
  - service: script.agile_charge_battery
    data:
      title: session 4
      message: >-
        session 4 ran successfully at {{"\r\n"}}'({{now().strftime("%Y-%m-%d
        %H:%M:%S")}})' {{"\r\n"}} cost is
        "{{states('input_text.session_4_cost')}}"
      messagenotenabled: session 4 is not enabled
      messagefailstart: session 4  failed to load start time retrying
      messagefailend: session 4  failed to load end time retrying
      messageloadstart: >-
        start time of "{{states('input_text.session_4_start')}}" {{"\r\n"}}
        Loaded
      messageloadend: end time of "{{states('input_text.session_4_end')}}" {{"\r\n"}} Loaded
      notification_id: id-004
      ses_detail: session_4_detail
      ses_cost: session_4_cost
      ses_start: session_4_start
      ses_end: session_4_end
      ses_enabled: session_4_enable
mode: restart