alias: Agile_selected_session_4
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.minutes_until_session_4
    to: "0"
    for:
      hours: 00
      minutes: 00
      seconds: 30
action:
  - service: script.agile_sol_check_control
    data: {}
  - service: script.agile_charge_battery
    data:
      title: Agile Import Session 4
      message: >-
        session 4 ran successfully at {{"\r\n"}}'({{now().strftime("%Y-%m-%d
        %H:%M:%S")}})' {{"\r\n"}} cost is
        "{{states('input_text.session_4_cost')}}"
      messagenotenabled: >-
        Soc is higher than target or {{"\r\n"}}  session 4 not enabled
        {{"\r\n"}}  Soc target "{{states('input_number.target_soc')}}"
        {{"\r\n"}} enabled is "{{states('input_boolean.session_4_enable')}}"
      messagefailstart: session 4  failed to load start time retrying
      messagefailend: session 4  failed to load end time retrying
      messageloadstart: >-
        start time of "{{states('input_text.session_4_start')}}" {{"\r\n"}}
        Loaded
      messageloadend: end time of "{{states('input_text.session_4_end')}}" {{"\r\n"}} Loaded
      notification_id: id-004
      ses_detail: session_4_detail
      ses_cost: session_4_cost
      ses_start: session_4_start
      ses_end: session_4_end
      ses_enabled: session_4_enable
mode: restart