alias: Agile_selected_session_2
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.minutes_until_session_2
    to: "0"
    for:
      hours: 0
      minutes: 0
      seconds: 20
action:
  - service: script.agile_charge_battery
    data:
      title: session 2
      message: >-
        session 2 ran successfully at {{"\r\n"}}'({{now().strftime("%Y-%m-%d
        %H:%M:%S")}})' {{"\r\n"}} cost is
        "{{states('input_text.session_2_cost')}}"
      messagenotenabled: session 2 is not enabled
      messagefailstart: session 2  failed to load start time retrying
      messagefailend: session 2  failed to load end time retrying
      messageloadstart: >-
        start time of "{{states('input_text.session_2_start')}}" {{"\r\n"}}
        Loaded
      messageloadend: end time of "{{states('input_text.session_2_end')}}" {{"\r\n"}} Loaded
      notification_id: id-002
      ses_detail: session_2_detail
      ses_cost: session_2_cost
      ses_start: session_2_start
      ses_end: session_2_end
      ses_enabled: session_2_enable
mode: restart