alias: LoadAgile
description: ""
trigger:
  - platform: time
    at: "17:10:00"
condition: []
action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.octopus_agile_range_ordered
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.Run_number1 }}"
    target:
      entity_id: input_text.session_1_detail
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.Run_number2 }}"
    target:
      entity_id: input_text.session_2_detail
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.Run_number3 }}"
    target:
      entity_id: input_text.session_3_detail
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.Run_number4 }}"
    target:
      entity_id: input_text.session_4_detail
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.Run_number5 }}"
    target:
      entity_id: input_text.session_5_detail
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.Run_number6 }}"
    target:
      entity_id: input_text.session_6_detail
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.Run_number7 }}"
    target:
      entity_id: input_text.session_7_detail
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.Run_number8 }}"
    target:
      entity_id: input_text.session_8_detail
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.Run_number9 }}"
    target:
      entity_id: input_text.session_9_detail
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.Run_number10 }}"
    target:
      entity_id: input_text.session_10_detail
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.cost_number1 }}"
    target:
      entity_id: input_text.session_1_cost
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.cost_number2 }}"
    target:
      entity_id: input_text.session_2_cost
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.cost_number3 }}"
    target:
      entity_id: input_text.session_3_cost
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.cost_number4 }}"
    target:
      entity_id: input_text.session_4_cost
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.cost_number5 }}"
    target:
      entity_id: input_text.session_5_cost
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.cost_number6 }}"
    target:
      entity_id: input_text.session_6_cost
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.cost_number7 }}"
    target:
      entity_id: input_text.session_7_cost
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.cost_number8 }}"
    target:
      entity_id: input_text.session_8_cost
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.cost_number9 }}"
    target:
      entity_id: input_text.session_9_cost
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.cost_number10 }}"
    target:
      entity_id: input_text.session_10_cost
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.start_time1 }}"
    target:
      entity_id: input_text.session_1_start
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.start_time2 }}"
    target:
      entity_id: input_text.session_2_start
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.start_time3 }}"
    target:
      entity_id: input_text.session_3_start
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.start_time4 }}"
    target:
      entity_id: input_text.session_4_start
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.start_time5 }}"
    target:
      entity_id: input_text.session_5_start
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.start_time6 }}"
    target:
      entity_id: input_text.session_6_start
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.start_time7 }}"
    target:
      entity_id: input_text.session_7_start
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.start_time8 }}"
    target:
      entity_id: input_text.session_8_start
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.start_time9 }}"
    target:
      entity_id: input_text.session_9_start
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.start_time10 }}"
    target:
      entity_id: input_text.session_10_start
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.end_time1 }}"
    target:
      entity_id: input_text.session_1_end
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.end_time2 }}"
    target:
      entity_id: input_text.session_2_end
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.end_time3 }}"
    target:
      entity_id: input_text.session_3_end
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.end_time4 }}"
    target:
      entity_id: input_text.session_4_end
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.end_time5 }}"
    target:
      entity_id: input_text.session_5_end
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.end_time6 }}"
    target:
      entity_id: input_text.session_6_end
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.end_time7 }}"
    target:
      entity_id: input_text.session_7_end
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.end_time8 }}"
    target:
      entity_id: input_text.session_8_end
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.end_time9 }}"
    target:
      entity_id: input_text.session_9_end
  - service: input_text.set_value
    data:
      value: "{{ states.sensor.octopus_agile_range_ordered.attributes.end_time10 }}"
    target:
      entity_id: input_text.session_10_end
  - service: script.agile_cost_loading
    data:
      ses_cost: session_1_cost
      ses_enabled: session_1_enable
  - service: script.agile_cost_loading
    data:
      ses_cost: session_2_cost
      ses_enabled: session_2_enable
  - service: script.agile_cost_loading
    data:
      ses_cost: session_3_cost
      ses_enabled: session_3_enable
  - service: script.agile_cost_loading
    data:
      ses_cost: session_4_cost
      ses_enabled: session_4_enable
  - service: script.agile_cost_loading
    data:
      ses_cost: session_5_cost
      ses_enabled: session_5_enable
  - service: script.agile_cost_loading
    data:
      ses_cost: session_6_cost
      ses_enabled: session_6_enable
  - service: script.agile_cost_loading
    data:
      ses_cost: session_7_cost
      ses_enabled: session_7_enable
  - service: script.agile_cost_loading
    data:
      ses_cost: session_8_cost
      ses_enabled: session_8_enable
  - service: script.agile_cost_loading
    data:
      ses_cost: session_9_cost
      ses_enabled: session_9_enable
  - service: script.agile_cost_loading
    data:
      ses_cost: session_10_cost
      ses_enabled: session_10_enable
mode: single
