alias: Agile_selected_session_9
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.minutes_until_session_9
    to: "0"
    for:
      hours: 0
      minutes: 0
      seconds: 30
action:
  - service: script.agile_charge_battery
    data:
      title: session 9
      message: >-
        session 9 ran successfully at {{"\r\n"}}'({{now().strftime("%Y-%m-%d
        %H:%M:%S")}})' {{"\r\n"}} cost is
        "{{states('input_text.session_9_cost')}}"
      messagenotenabled: session 9 is not enabled
      messagefailstart: session 9  failed to load start time retrying
      messagefailend: session 9  failed to load end time retrying
      messageloadstart: >-
        start time of "{{states('input_text.session_9_start')}}" {{"\r\n"}}
        Loaded
      messageloadend: end time of "{{states('input_text.session_9_end')}}" {{"\r\n"}} Loaded
      notification_id: id-009
      ses_detail: session_9_detail
      ses_cost: session_9_cost
      ses_start: session_9_start
      ses_end: session_9_end
      ses_enabled: session_9_enable
mode: restart
