alias: Agile_selected_session_10
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.minutes_until_session_10
    to: "0"
    for:
      hours: 0
      minutes: 0
      seconds: 30
action:
  - service: script.agile_sol_check_control
    data: {}
  - service: script.agile_charge_battery
    data:
      title: Agile Import Session 10
      message: >-
        session 10 ran successfully at {{"\r\n"}}'({{now().strftime("%Y-%m-%d
        %H:%M:%S")}})' {{"\r\n"}} cost is
        "{{states('input_text.session_10_cost')}}"
      messagenotenabled: >-
        Soc is higher than target or {{"\r\n"}}  session 10 not enabled
        {{"\r\n"}}  Soc target "{{states('input_number.target_soc')}}"
        {{"\r\n"}} enabled is "{{states('input_boolean.session_10_enable')}}"
      messagefailstart: session 10  failed to load start time retrying
      messagefailend: session 10  failed to load end time retrying
      messageloadstart: >-
        start time of "{{states('input_text.session_10_start')}}" {{"\r\n"}}
        Loaded
      messageloadend: end time of "{{states('input_text.session_10_end')}}" {{"\r\n"}} Loaded
      notification_id: id-010
      ses_detail: session_10_detail
      ses_cost: session_10_cost
      ses_start: session_10_start
      ses_end: session_10_end
      ses_enabled: session_10_enable
mode: restart
