alias: Agile_selected_session_7
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.minutes_until_session_7
    to: "0"
    for:
      hours: 00
      minutes: 00
      seconds: 30
action:
  - service: script.agile_sol_check_control
    data: {}
  - service: script.agile_charge_battery
    data:
      title: Agile Import Session 7
      message: >-
        session 7 ran successfully at {{"\r\n"}}'({{now().strftime("%Y-%m-%d
        %H:%M:%S")}})' {{"\r\n"}} cost is
        "{{states('input_text.session_7_cost')}}"
      messagenotenabled: >-
        Soc is higher than target or {{"\r\n"}}  session 7 not enabled
        {{"\r\n"}}  Soc target "{{states('input_number.target_soc')}}"
        {{"\r\n"}} enabled is "{{states('input_boolean.session_7_enable')}}"
      messagefailstart: session 7  failed to load start time retrying
      messagefailend: session 7  failed to load end time retrying
      messageloadstart: >-
        start time of "{{states('input_text.session_7_start')}}" {{"\r\n"}}
        Loaded
      messageloadend: end time of "{{states('input_text.session_7_end')}}" {{"\r\n"}} Loaded
      notification_id: id-007
      ses_detail: session_7_detail
      ses_cost: session_7_cost
      ses_start: session_7_start
      ses_end: session_7_end
      ses_enabled: session_7_enable
mode: restart